# Properties of chemical elements

PT <- list()

# The number of electrons
PT$NumEl <- list()
PT$NumEl[["H"]]  <- 1
PT$NumEl[["He"]] <- 2
PT$NumEl[["Li"]] <- 3
PT$NumEl[["Be"]] <- 4
PT$NumEl[["B"]]  <- 5
PT$NumEl[["C"]]  <- 6
PT$NumEl[["N"]]  <- 7
PT$NumEl[["O"]]  <- 8
PT$NumEl[["F"]]  <- 9
PT$NumEl[["Ne"]] <- 10
PT$NumEl[["Na"]] <- 11
PT$NumEl[["Mg"]] <- 12
PT$NumEl[["Al"]] <- 13
PT$NumEl[["Si"]] <- 14
PT$NumEl[["P"]]  <- 15
PT$NumEl[["S"]]  <- 16
PT$NumEl[["Cl"]] <- 17
PT$NumEl[["Ar"]] <- 18
PT$NumEl[["K"]]  <- 19
PT$NumEl[["Ca"]] <- 20
PT$NumEl[["Sc"]] <- 21
PT$NumEl[["Ti"]] <- 22
PT$NumEl[["V"]]  <- 23
PT$NumEl[["Cr"]] <- 24
PT$NumEl[["Mn"]] <- 25
PT$NumEl[["Fe"]] <- 26
PT$NumEl[["Co"]] <- 27
PT$NumEl[["Ni"]] <- 28
PT$NumEl[["Cu"]] <- 29
PT$NumEl[["Zn"]] <- 30
PT$NumEl[["Ga"]] <- 31
PT$NumEl[["Ge"]] <- 32
PT$NumEl[["As"]] <- 33
PT$NumEl[["Se"]] <- 34
PT$NumEl[["Br"]] <- 35
PT$NumEl[["Kr"]] <- 36
PT$NumEl[["Rb"]] <- 37
PT$NumEl[["Sr"]] <- 38
PT$NumEl[["Y"]]  <- 39
PT$NumEl[["Zr"]] <- 40
PT$NumEl[["Nb"]] <- 41
PT$NumEl[["Mo"]] <- 42
PT$NumEl[["Tc"]] <- 43
PT$NumEl[["Ru"]] <- 44
PT$NumEl[["Rh"]] <- 45
PT$NumEl[["Pd"]] <- 46
PT$NumEl[["Ag"]] <- 47
PT$NumEl[["Cd"]] <- 48
PT$NumEl[["In"]] <- 49
PT$NumEl[["Sn"]] <- 50
PT$NumEl[["Sb"]] <- 51
PT$NumEl[["Te"]] <- 52
PT$NumEl[["I"]]  <- 53
PT$NumEl[["Xe"]] <- 54
PT$NumEl[["Cs"]] <- 55
PT$NumEl[["Ba"]] <- 56
PT$NumEl[["La"]] <- 57
PT$NumEl[["Ce"]] <- 58
PT$NumEl[["Pr"]] <- 59
PT$NumEl[["Nd"]] <- 60
PT$NumEl[["Pm"]] <- 61
PT$NumEl[["Sm"]] <- 62
PT$NumEl[["Eu"]] <- 63
PT$NumEl[["Gd"]] <- 64
PT$NumEl[["Tb"]] <- 65
PT$NumEl[["Dy"]] <- 66
PT$NumEl[["Ho"]] <- 67
PT$NumEl[["Er"]] <- 68
PT$NumEl[["Tm"]] <- 69
PT$NumEl[["Yb"]] <- 70
PT$NumEl[["Lu"]] <- 71
PT$NumEl[["Hf"]] <- 72
PT$NumEl[["Ta"]] <- 73
PT$NumEl[["W"]]  <- 74
PT$NumEl[["Re"]] <- 75
PT$NumEl[["Os"]] <- 76
PT$NumEl[["Ir"]] <- 77
PT$NumEl[["Pt"]] <- 78
PT$NumEl[["Au"]] <- 79
PT$NumEl[["Hg"]] <- 80
PT$NumEl[["Tl"]] <- 81
PT$NumEl[["Pb"]] <- 82
PT$NumEl[["Bi"]] <- 83
PT$NumEl[["Po"]] <- 84
PT$NumEl[["Th"]] <- 90
PT$NumEl[["U"]]  <- 92

# The number of valent electrons
PT$NumValEl <- list()
PT$NumValEl[["H"]]  <- 1
PT$NumValEl[["He"]] <- 2
PT$NumValEl[["Li"]] <- 1
PT$NumValEl[["Be"]] <- 2
PT$NumValEl[["B"]]  <- 3
PT$NumValEl[["C"]]  <- 4
PT$NumValEl[["N"]]  <- 5
PT$NumValEl[["O"]]  <- 6
PT$NumValEl[["F"]]  <- 7
PT$NumValEl[["Ne"]] <- 8
PT$NumValEl[["Na"]] <- 1
PT$NumValEl[["Mg"]] <- 2
PT$NumValEl[["Al"]] <- 3
PT$NumValEl[["Si"]] <- 4
PT$NumValEl[["P"]]  <- 5
PT$NumValEl[["S"]]  <- 6
PT$NumValEl[["Cl"]] <- 7
PT$NumValEl[["Ar"]] <- 8
PT$NumValEl[["K"]]  <- 1
PT$NumValEl[["Ca"]] <- 2
PT$NumValEl[["Sc"]] <- 3
PT$NumValEl[["Ti"]] <- 4
PT$NumValEl[["V"]]  <- 5
PT$NumValEl[["Cr"]] <- 6
PT$NumValEl[["Mn"]] <- 7
PT$NumValEl[["Fe"]] <- 8
PT$NumValEl[["Co"]] <- 9
PT$NumValEl[["Ni"]] <- 10
PT$NumValEl[["Cu"]] <- 11
PT$NumValEl[["Zn"]] <- 12
PT$NumValEl[["Ga"]] <- 13
PT$NumValEl[["Ge"]] <- 14
PT$NumValEl[["As"]] <- 15
PT$NumValEl[["Se"]] <- 16
PT$NumValEl[["Br"]] <- 17
PT$NumValEl[["Kr"]] <- 18
PT$NumValEl[["Rb"]] <- 1
PT$NumValEl[["Sr"]] <- 2
PT$NumValEl[["Y"]]  <- 3
PT$NumValEl[["Zr"]] <- 4
PT$NumValEl[["Nb"]] <- 5
PT$NumValEl[["Mo"]] <- 6
PT$NumValEl[["Tc"]] <- 7
PT$NumValEl[["Ru"]] <- 8
PT$NumValEl[["Rh"]] <- 9
PT$NumValEl[["Pd"]] <- 10
PT$NumValEl[["Ag"]] <- 11
PT$NumValEl[["Cd"]] <- 12
PT$NumValEl[["In"]] <- 13
PT$NumValEl[["Sn"]] <- 14
PT$NumValEl[["Sb"]] <- 15
PT$NumValEl[["Te"]] <- 16
PT$NumValEl[["I"]]  <- 17
PT$NumValEl[["Xe"]] <- 18
PT$NumValEl[["Cs"]] <- 1
PT$NumValEl[["Ba"]] <- 2
PT$NumValEl[["La"]] <- 3
PT$NumValEl[["Ce"]] <- 4
PT$NumValEl[["Pr"]] <- 5
PT$NumValEl[["Nd"]] <- 6
PT$NumValEl[["Pm"]] <- 7
PT$NumValEl[["Sm"]] <- 8
PT$NumValEl[["Eu"]] <- 9
PT$NumValEl[["Gd"]] <- 10
PT$NumValEl[["Tb"]] <- 11
PT$NumValEl[["Dy"]] <- 12
PT$NumValEl[["Ho"]] <- 13
PT$NumValEl[["Er"]] <- 14
PT$NumValEl[["Tm"]] <- 15
PT$NumValEl[["Yb"]] <- 16
PT$NumValEl[["Lu"]] <- 17
PT$NumValEl[["Hf"]] <- 18
PT$NumValEl[["Ta"]] <- 19
PT$NumValEl[["W"]]  <- 20
PT$NumValEl[["Re"]] <- 21
PT$NumValEl[["Os"]] <- 22
PT$NumValEl[["Ir"]] <- 23
PT$NumValEl[["Pt"]] <- 24
PT$NumValEl[["Au"]] <- 25
PT$NumValEl[["Hg"]] <- 26
PT$NumValEl[["Tl"]] <- 27
PT$NumValEl[["Pb"]] <- 28
PT$NumValEl[["Bi"]] <- 29
PT$NumValEl[["Po"]] <- 30
PT$NumValEl[["Th"]] <- 4
PT$NumValEl[["U"]]  <- 6

# Common valence o atoms
PT$ComVal <- list()
PT$ComVal[["H"]]  <- 1
PT$ComVal[["He"]] <- 0
PT$ComVal[["Li"]] <- 0
PT$ComVal[["Be"]] <- 0
PT$ComVal[["B"]]  <- 3
PT$ComVal[["C"]]  <- 4
PT$ComVal[["N"]]  <- 3
PT$ComVal[["O"]]  <- 2
PT$ComVal[["F"]]  <- 1
PT$ComVal[["Ne"]] <- 0
PT$ComVal[["Na"]] <- 0
PT$ComVal[["Mg"]] <- 0
PT$ComVal[["Al"]] <- 0
PT$ComVal[["Si"]] <- 4
PT$ComVal[["P"]]  <- 3
PT$ComVal[["S"]]  <- 2
PT$ComVal[["Cl"]] <- 1
PT$ComVal[["Ar"]] <- 0
PT$ComVal[["K"]]  <- 0
PT$ComVal[["Ca"]] <- 0
PT$ComVal[["Sc"]] <- 0
PT$ComVal[["Ti"]] <- 0
PT$ComVal[["V"]]  <- 0
PT$ComVal[["Cr"]] <- 0
PT$ComVal[["Mn"]] <- 0
PT$ComVal[["Fe"]] <- 0
PT$ComVal[["Co"]] <- 0
PT$ComVal[["Ni"]] <- 0
PT$ComVal[["Cu"]] <- 0
PT$ComVal[["Zn"]] <- 0
PT$ComVal[["Ga"]] <- 0
PT$ComVal[["Ge"]] <- 0
PT$ComVal[["As"]] <- 3
PT$ComVal[["Se"]] <- 2
PT$ComVal[["Br"]] <- 1
PT$ComVal[["Kr"]] <- 0
PT$ComVal[["Rb"]] <- 0
PT$ComVal[["Sr"]] <- 0
PT$ComVal[["Y"]]  <- 0
PT$ComVal[["Zr"]] <- 0
PT$ComVal[["Nb"]] <- 0
PT$ComVal[["Mo"]] <- 0
PT$ComVal[["Tc"]] <- 0
PT$ComVal[["Ru"]] <- 0
PT$ComVal[["Rh"]] <- 0
PT$ComVal[["Pd"]] <- 0
PT$ComVal[["Ag"]] <- 0
PT$ComVal[["Cd"]] <- 0
PT$ComVal[["In"]] <- 0
PT$ComVal[["Sn"]] <- 0
PT$ComVal[["Sb"]] <- 0
PT$ComVal[["Te"]] <- 2
PT$ComVal[["I"]]  <- 1
PT$ComVal[["Xe"]] <- 0
PT$ComVal[["Cs"]] <- 0
PT$ComVal[["Ba"]] <- 0
PT$ComVal[["La"]] <- 0
PT$ComVal[["Ce"]] <- 0
PT$ComVal[["Pr"]] <- 0
PT$ComVal[["Nd"]] <- 0
PT$ComVal[["Pm"]] <- 0
PT$ComVal[["Sm"]] <- 0
PT$ComVal[["Eu"]] <- 0
PT$ComVal[["Gd"]] <- 0
PT$ComVal[["Tb"]] <- 0
PT$ComVal[["Dy"]] <- 0
PT$ComVal[["Ho"]] <- 0
PT$ComVal[["Er"]] <- 0
PT$ComVal[["Tm"]] <- 0
PT$ComVal[["Yb"]] <- 0
PT$ComVal[["Lu"]] <- 0
PT$ComVal[["Hf"]] <- 0
PT$ComVal[["Ta"]] <- 0
PT$ComVal[["W"]]  <- 0
PT$ComVal[["Re"]] <- 0
PT$ComVal[["Os"]] <- 0
PT$ComVal[["Ir"]] <- 0
PT$ComVal[["Pt"]] <- 0
PT$ComVal[["Au"]] <- 0
PT$ComVal[["Hg"]] <- 0
PT$ComVal[["Tl"]] <- 0
PT$ComVal[["Pb"]] <- 0
PT$ComVal[["Bi"]] <- 0
PT$ComVal[["Po"]] <- 0
PT$ComVal[["Th"]] <- 0
PT$ComVal[["U"]]  <- 0

# Maximum valence o atoms
PT$MaxVal <- list()
PT$MaxVal[["H"]]  <- 1
PT$MaxVal[["He"]] <- 0
PT$MaxVal[["Li"]] <- 0
PT$MaxVal[["Be"]] <- 0
PT$MaxVal[["B"]]  <- 5
PT$MaxVal[["C"]]  <- 4
PT$MaxVal[["N"]]  <- 5
PT$MaxVal[["O"]]  <- 4
PT$MaxVal[["F"]]  <- 1
PT$MaxVal[["Ne"]] <- 0
PT$MaxVal[["Na"]] <- 0
PT$MaxVal[["Mg"]] <- 0
PT$MaxVal[["Al"]] <- 0
PT$MaxVal[["Si"]] <- 4
PT$MaxVal[["P"]]  <- 5
PT$MaxVal[["S"]]  <- 6
PT$MaxVal[["Cl"]] <- 7
PT$MaxVal[["Ar"]] <- 0
PT$MaxVal[["K"]]  <- 0
PT$MaxVal[["Ca"]] <- 0
PT$MaxVal[["Sc"]] <- 0
PT$MaxVal[["Ti"]] <- 0
PT$MaxVal[["V"]]  <- 0
PT$MaxVal[["Cr"]] <- 0
PT$MaxVal[["Mn"]] <- 0
PT$MaxVal[["Fe"]] <- 0
PT$MaxVal[["Co"]] <- 0
PT$MaxVal[["Ni"]] <- 0
PT$MaxVal[["Cu"]] <- 0
PT$MaxVal[["Zn"]] <- 0
PT$MaxVal[["Ga"]] <- 0
PT$MaxVal[["Ge"]] <- 0
PT$MaxVal[["As"]] <- 5
PT$MaxVal[["Se"]] <- 6
PT$MaxVal[["Br"]] <- 7
PT$MaxVal[["Kr"]] <- 0
PT$MaxVal[["Rb"]] <- 0
PT$MaxVal[["Sr"]] <- 0
PT$MaxVal[["Y"]]  <- 0
PT$MaxVal[["Zr"]] <- 0
PT$MaxVal[["Nb"]] <- 0
PT$MaxVal[["Mo"]] <- 0
PT$MaxVal[["Tc"]] <- 0
PT$MaxVal[["Ru"]] <- 0
PT$MaxVal[["Rh"]] <- 0
PT$MaxVal[["Pd"]] <- 0
PT$MaxVal[["Ag"]] <- 0
PT$MaxVal[["Cd"]] <- 0
PT$MaxVal[["In"]] <- 0
PT$MaxVal[["Sn"]] <- 0
PT$MaxVal[["Sb"]] <- 0
PT$MaxVal[["Te"]] <- 6
PT$MaxVal[["I"]]  <- 7
PT$MaxVal[["Xe"]] <- 0
PT$MaxVal[["Cs"]] <- 0
PT$MaxVal[["Ba"]] <- 0
PT$MaxVal[["La"]] <- 0
PT$MaxVal[["Ce"]] <- 0
PT$MaxVal[["Pr"]] <- 0
PT$MaxVal[["Nd"]] <- 0
PT$MaxVal[["Pm"]] <- 0
PT$MaxVal[["Sm"]] <- 0
PT$MaxVal[["Eu"]] <- 0
PT$MaxVal[["Gd"]] <- 0
PT$MaxVal[["Tb"]] <- 0
PT$MaxVal[["Dy"]] <- 0
PT$MaxVal[["Ho"]] <- 0
PT$MaxVal[["Er"]] <- 0
PT$MaxVal[["Tm"]] <- 0
PT$MaxVal[["Yb"]] <- 0
PT$MaxVal[["Lu"]] <- 0
PT$MaxVal[["Hf"]] <- 0
PT$MaxVal[["Ta"]] <- 0
PT$MaxVal[["W"]]  <- 0
PT$MaxVal[["Re"]] <- 0
PT$MaxVal[["Os"]] <- 0
PT$MaxVal[["Ir"]] <- 0
PT$MaxVal[["Pt"]] <- 0
PT$MaxVal[["Au"]] <- 0
PT$MaxVal[["Hg"]] <- 0
PT$MaxVal[["Tl"]] <- 0
PT$MaxVal[["Pb"]] <- 0
PT$MaxVal[["Bi"]] <- 0
PT$MaxVal[["Po"]] <- 0
PT$MaxVal[["Th"]] <- 0
PT$MaxVal[["U"]]  <- 0

# Atomic weight
PT$AW <- list()
PT$AW[["H"]]  <- 1.008
PT$AW[["He"]] <- 4.00260
PT$AW[["Li"]] <- 6.94
PT$AW[["Be"]] <- 9.01218
PT$AW[["B"]]  <- 10.81
PT$AW[["C"]]  <- 12.011
PT$AW[["N"]]  <- 14.0067
PT$AW[["O"]]  <- 15.9994
PT$AW[["F"]]  <- 18.9984
PT$AW[["Ne"]] <- 20.17
PT$AW[["Na"]] <- 22.9898
PT$AW[["Mg"]] <- 24.305
PT$AW[["Al"]] <- 26.9815
PT$AW[["Si"]] <- 28.086
PT$AW[["P"]]  <- 30.9738
PT$AW[["S"]]  <- 32.06
PT$AW[["Cl"]] <- 35.453
PT$AW[["Ar"]] <- 39.948
PT$AW[["K"]]  <- 39.102
PT$AW[["Ca"]] <- 40.08
PT$AW[["Sc"]] <- 44.9559
PT$AW[["Ti"]] <- 47.90
PT$AW[["V"]]  <- 50.941
PT$AW[["Cr"]] <- 51.996
PT$AW[["Mn"]] <- 54.9380
PT$AW[["Fe"]] <- 55.847
PT$AW[["Co"]] <- 58.9332
PT$AW[["Ni"]] <- 58.71
PT$AW[["Cu"]] <- 63.546
PT$AW[["Zn"]] <- 65.37
PT$AW[["Ga"]] <- 69.72
PT$AW[["Ge"]] <- 72.59
PT$AW[["As"]] <- 74.9216
PT$AW[["Se"]] <- 78.96
PT$AW[["Br"]] <- 79.904
PT$AW[["Kr"]] <- 83.80
PT$AW[["Rb"]] <- 85.467
PT$AW[["Sr"]] <- 87.62
PT$AW[["Y"]]  <- 88.9059
PT$AW[["Zr"]] <- 91.22
PT$AW[["Nb"]] <- 92.9064
PT$AW[["Mo"]] <- 95.94
PT$AW[["Tc"]] <- 98.9062
PT$AW[["Ru"]] <- 101.07
PT$AW[["Rh"]] <- 102.9055
PT$AW[["Pd"]] <- 106.4
PT$AW[["Ag"]] <- 107.868
PT$AW[["Cd"]] <- 112.40
PT$AW[["In"]] <- 114.82
PT$AW[["Sn"]] <- 118.69
PT$AW[["Sb"]] <- 121.75
PT$AW[["Te"]] <- 127.60
PT$AW[["I"]]  <- 126.9045
PT$AW[["Xe"]] <- 131.30
PT$AW[["Cs"]] <- 132.9055
PT$AW[["Ba"]] <- 137.34
PT$AW[["La"]] <- 138.9055
PT$AW[["Ce"]] <- 140.12
PT$AW[["Pr"]] <- 140.9077
PT$AW[["Nd"]] <- 144.24
PT$AW[["Pm"]] <- 145.0
PT$AW[["Sm"]] <- 150.4
PT$AW[["Eu"]] <- 151.96
PT$AW[["Gd"]] <- 157.25
PT$AW[["Tb"]] <- 158.9254
PT$AW[["Dy"]] <- 162.50
PT$AW[["Ho"]] <- 164.9303
PT$AW[["Er"]] <- 167.26
PT$AW[["Tm"]] <- 168.9342
PT$AW[["Yb"]] <- 173.04
PT$AW[["Lu"]] <- 174.97
PT$AW[["Hf"]] <- 178.49
PT$AW[["Ta"]] <- 180.947
PT$AW[["W"]]  <- 183.85
PT$AW[["Re"]] <- 186.2
PT$AW[["Os"]] <- 190.2
PT$AW[["Ir"]] <- 192.22
PT$AW[["Pt"]] <- 195.09
PT$AW[["Au"]] <- 196.9665
PT$AW[["Hg"]] <- 200.59
PT$AW[["Tl"]] <- 204.37
PT$AW[["Pb"]] <- 207.2
PT$AW[["Bi"]] <- 208.9806
PT$AW[["Po"]] <- 209.0
PT$AW[["Th"]] <- 232.0381
PT$AW[["U"]]  <- 238.029

# Electronegativity
PT$ElNeg <- list()
PT$ElNeg[["H"]]  <- 2.27
PT$ElNeg[["He"]] <- 3.92
PT$ElNeg[["Li"]] <- 0.94
PT$ElNeg[["Be"]] <- 1.55
PT$ElNeg[["B"]]  <- 2.02
PT$ElNeg[["C"]]  <- 2.55
PT$ElNeg[["N"]]  <- 3.12
PT$ElNeg[["O"]]  <- 3.62
PT$ElNeg[["F"]]  <- 4.23
PT$ElNeg[["Ne"]] <- 4.89
PT$ElNeg[["Na"]] <- 0.95
PT$ElNeg[["Mg"]] <- 1.32
PT$ElNeg[["Al"]] <- 1.55
PT$ElNeg[["Si"]] <- 1.87
PT$ElNeg[["P"]]  <- 2.22
PT$ElNeg[["S"]]  <- 2.49
PT$ElNeg[["Cl"]] <- 2.82
PT$ElNeg[["Ar"]] <- 3.18
PT$ElNeg[["K"]]  <- 0.84
PT$ElNeg[["Ca"]] <- 1.11
PT$ElNeg[["Sc"]] <- 1.17
PT$ElNeg[["Ti"]] <- 1.23
PT$ElNeg[["V"]]  <- 1.27
PT$ElNeg[["Cr"]] <- 1.29
PT$ElNeg[["Mn"]] <- 1.36
PT$ElNeg[["Fe"]] <- 1.40
PT$ElNeg[["Co"]] <- 1.44
PT$ElNeg[["Ni"]] <- 1.47
PT$ElNeg[["Cu"]] <- 1.51
PT$ElNeg[["Zn"]] <- 1.46
PT$ElNeg[["Ga"]] <- 1.56
PT$ElNeg[["Ge"]] <- 1.81
PT$ElNeg[["As"]] <- 2.11
PT$ElNeg[["Se"]] <- 2.31
PT$ElNeg[["Br"]] <- 2.56
PT$ElNeg[["Kr"]] <- 2.82
PT$ElNeg[["Rb"]] <- 0.83
PT$ElNeg[["Sr"]] <- 1.06
PT$ElNeg[["Y"]]  <- 1.11
PT$ElNeg[["Zr"]] <- 1.17
PT$ElNeg[["Nb"]] <- 1.21
PT$ElNeg[["Mo"]] <- 1.26
PT$ElNeg[["Tc"]] <- 1.30
PT$ElNeg[["Ru"]] <- 1.35
PT$ElNeg[["Rh"]] <- 1.39
PT$ElNeg[["Pd"]] <- 1.61
PT$ElNeg[["Ag"]] <- 1.45
PT$ElNeg[["Cd"]] <- 1.45
PT$ElNeg[["In"]] <- 1.52
PT$ElNeg[["Sn"]] <- 1.70
PT$ElNeg[["Sb"]] <- 1.88
PT$ElNeg[["Te"]] <- 2.08
PT$ElNeg[["I"]]  <- 2.27
PT$ElNeg[["Xe"]] <- 2.45
PT$ElNeg[["Cs"]] <- 0.79
PT$ElNeg[["Ba"]] <- 0.98
PT$ElNeg[["La"]] <- 1.04
PT$ElNeg[["Ce"]] <- 1.05
PT$ElNeg[["Pr"]] <- 1.06
PT$ElNeg[["Nd"]] <- 1.03
#PT$ElNeg[["Pm"]] <- 
PT$ElNeg[["Sm"]] <- 1.05
PT$ElNeg[["Eu"]] <- 1.06
PT$ElNeg[["Gd"]] <- 1.10
PT$ElNeg[["Tb"]] <- 1.08
PT$ElNeg[["Dy"]] <- 1.09
PT$ElNeg[["Ho"]] <- 1.10
PT$ElNeg[["Er"]] <- 1.11
PT$ElNeg[["Tm"]] <- 1.12
PT$ElNeg[["Yb"]] <- 1.13
PT$ElNeg[["Lu"]] <- 1.12
PT$ElNeg[["Hf"]] <- 1.20
PT$ElNeg[["Ta"]] <- 1.26
PT$ElNeg[["W"]]  <- 1.31
PT$ElNeg[["Re"]] <- 1.35
PT$ElNeg[["Os"]] <- 1.39
PT$ElNeg[["Ir"]] <- 1.43
PT$ElNeg[["Pt"]] <- 1.49
PT$ElNeg[["Au"]] <- 1.53
PT$ElNeg[["Hg"]] <- 1.54
PT$ElNeg[["Tl"]] <- 1.59
PT$ElNeg[["Pb"]] <- 1.76
PT$ElNeg[["Bi"]] <- 1.83
PT$ElNeg[["Po"]] <- 1.96
PT$ElNeg[["Th"]] <- 1.03
PT$ElNeg[["U"]]  <- 1.06

# Atomic radius
PT$AtRad <- list()
PT$AtRad[["H"]]  <- 0.529
PT$AtRad[["He"]] <- 0.9
PT$AtRad[["Li"]] <- 1.5
PT$AtRad[["Be"]] <- 1.12
PT$AtRad[["B"]]  <- 0.98 
PT$AtRad[["C"]]  <- 0.914
PT$AtRad[["N"]]  <- 0.92
PT$AtRad[["O"]]  <- 0.6
PT$AtRad[["F"]]  <- 0.68
PT$AtRad[["Ne"]] <- 1.60
PT$AtRad[["Na"]] <- 1.9
PT$AtRad[["Mg"]] <- 1.60
PT$AtRad[["Al"]] <- 1.43
PT$AtRad[["Si"]] <- 1.32
PT$AtRad[["P"]]  <- 1.2
PT$AtRad[["S"]]  <- 1.27
PT$AtRad[["Cl"]] <- 0.98
PT$AtRad[["Ar"]] <- 1.91
PT$AtRad[["K"]]  <- 2.3
PT$AtRad[["Ca"]] <- 1.97
PT$AtRad[["Sc"]] <- 1.6
PT$AtRad[["Ti"]] <- 1.71
PT$AtRad[["V"]]  <- 1.3
PT$AtRad[["Cr"]] <- 1.27
PT$AtRad[["Mn"]] <- 1.26
PT$AtRad[["Fe"]] <- 1.26
PT$AtRad[["Co"]] <- 1.3
PT$AtRad[["Ni"]] <- 1.24
PT$AtRad[["Cu"]] <- 1.28
PT$AtRad[["Zn"]] <- 1.38
PT$AtRad[["Ga"]] <- 1.4
PT$AtRad[["Ge"]] <- 1.37
PT$AtRad[["As"]] <- 1.3
PT$AtRad[["Se"]] <- 1.3
PT$AtRad[["Br"]] <- 1.13
PT$AtRad[["Kr"]] <- 1.9
PT$AtRad[["Rb"]] <- 2.45
PT$AtRad[["Sr"]] <- 2.14
PT$AtRad[["Y"]]  <- 1.8
PT$AtRad[["Zr"]] <- 1.60
PT$AtRad[["Nb"]] <- 1.45
PT$AtRad[["Mo"]] <- 1.37
PT$AtRad[["Tc"]] <- 1.36
PT$AtRad[["Ru"]] <- 1.33
PT$AtRad[["Rh"]] <- 1.34
PT$AtRad[["Pd"]] <- 1.37
PT$AtRad[["Ag"]] <- 1.44
PT$AtRad[["Cd"]] <- 1.54
PT$AtRad[["In"]] <- 1.66
PT$AtRad[["Sn"]] <- 1.5
PT$AtRad[["Sb"]] <- 1.5
PT$AtRad[["Te"]] <- 1.60
PT$AtRad[["I"]]  <- 1.3
PT$AtRad[["Xe"]] <- 2.2
PT$AtRad[["Cs"]] <- 2.67
PT$AtRad[["Ba"]] <- 2.2
PT$AtRad[["La"]] <- 1.86
PT$AtRad[["Ce"]] <- 1.81
PT$AtRad[["Pr"]] <- 1.83
PT$AtRad[["Nd"]] <- 1.82
#PT$AtRad[["Pm"]] <- 
PT$AtRad[["Sm"]] <- 1.66
PT$AtRad[["Eu"]] <- 2.04
PT$AtRad[["Gd"]] <- 1.79
PT$AtRad[["Tb"]] <- 1.77
PT$AtRad[["Dy"]] <- 1.77
PT$AtRad[["Ho"]] <- 1.76
PT$AtRad[["Er"]] <- 1.75
PT$AtRad[["Tm"]] <- 1.74
PT$AtRad[["Yb"]] <- 1.93
PT$AtRad[["Lu"]] <- 1.74
PT$AtRad[["Hf"]] <- 1.7
PT$AtRad[["Ta"]] <- 1.45
PT$AtRad[["W"]]  <- 1.38
PT$AtRad[["Re"]] <- 1.37
PT$AtRad[["Os"]] <- 1.35
PT$AtRad[["Ir"]] <- 1.36
PT$AtRad[["Pt"]] <- 1.38
PT$AtRad[["Au"]] <- 1.44
PT$AtRad[["Hg"]] <- 1.57 
PT$AtRad[["Tl"]] <- 1.71
PT$AtRad[["Pb"]] <- 1.75
PT$AtRad[["Bi"]] <- 1.70
PT$AtRad[["Po"]] <- 1.76
PT$AtRad[["Th"]] <- 1.80
PT$AtRad[["U"]]  <- 1.5

# Ionization potential
PT$IonPot <- list()
PT$IonPot[["H"]]  <- 13.598
PT$IonPot[["He"]] <- 24.587
PT$IonPot[["Li"]] <- 5.392
PT$IonPot[["Be"]] <- 9.323
PT$IonPot[["B"]]  <- 8.298
PT$IonPot[["C"]]  <- 11.260
PT$IonPot[["N"]]  <- 14.534
PT$IonPot[["O"]]  <- 13.618
PT$IonPot[["F"]]  <- 17.423
PT$IonPot[["Ne"]] <- 21.565
PT$IonPot[["Na"]] <- 5.139
PT$IonPot[["Mg"]] <- 7.646
PT$IonPot[["Al"]] <- 5.986
PT$IonPot[["Si"]] <- 8.152
PT$IonPot[["P"]]  <- 10.487
PT$IonPot[["S"]]  <- 10.360
PT$IonPot[["Cl"]] <- 12.968
PT$IonPot[["Ar"]] <- 15.760
PT$IonPot[["K"]]  <- 4.341
PT$IonPot[["Ca"]] <- 6.113
PT$IonPot[["Sc"]] <- 6.562
PT$IonPot[["Ti"]] <- 6.828
PT$IonPot[["V"]]  <- 6.746
PT$IonPot[["Cr"]] <- 6.767
PT$IonPot[["Mn"]] <- 7.434
PT$IonPot[["Fe"]] <- 7.902
PT$IonPot[["Co"]] <- 7.881
PT$IonPot[["Ni"]] <- 7.640
PT$IonPot[["Cu"]] <- 7.726
PT$IonPot[["Zn"]] <- 9.394 
PT$IonPot[["Ga"]] <- 5.999
PT$IonPot[["Ge"]] <- 7.899
PT$IonPot[["As"]] <- 9.789
PT$IonPot[["Se"]] <- 9.752
PT$IonPot[["Br"]] <- 11.814
PT$IonPot[["Kr"]] <- 14.000
PT$IonPot[["Rb"]] <- 4.177
PT$IonPot[["Sr"]] <- 5.695
PT$IonPot[["Y"]]  <- 6.217
PT$IonPot[["Zr"]] <- 6.634
PT$IonPot[["Nb"]] <- 6.759
PT$IonPot[["Mo"]] <- 7.092
PT$IonPot[["Tc"]] <- 7.28
PT$IonPot[["Ru"]] <- 7.361 
PT$IonPot[["Rh"]] <- 7.459
PT$IonPot[["Pd"]] <- 8.337
PT$IonPot[["Ag"]] <- 7.576
PT$IonPot[["Cd"]] <- 8.994
PT$IonPot[["In"]] <- 5.786
PT$IonPot[["Sn"]] <- 7.344
PT$IonPot[["Sb"]] <- 8.608
PT$IonPot[["Te"]] <- 9.010
PT$IonPot[["I"]]  <- 10.451
PT$IonPot[["Xe"]] <- 12.130
PT$IonPot[["Cs"]] <- 3.894
PT$IonPot[["Ba"]] <- 5.212
PT$IonPot[["La"]] <- 5.577
PT$IonPot[["Ce"]] <- 5.539
PT$IonPot[["Pr"]] <- 5.473
PT$IonPot[["Nd"]] <- 5.525
PT$IonPot[["Pm"]] <- 5.582
PT$IonPot[["Sm"]] <- 5.644
PT$IonPot[["Eu"]] <- 5.670
PT$IonPot[["Gd"]] <- 6.150
PT$IonPot[["Tb"]] <- 5.864
PT$IonPot[["Dy"]] <- 5.939
PT$IonPot[["Ho"]] <- 6.022
PT$IonPot[["Er"]] <- 6.108
PT$IonPot[["Tm"]] <- 6.184
PT$IonPot[["Yb"]] <- 6.254
PT$IonPot[["Lu"]] <- 5.426
PT$IonPot[["Hf"]] <- 6.825
PT$IonPot[["Ta"]] <- 7.550
PT$IonPot[["W"]]  <- 7.864
PT$IonPot[["Re"]] <- 7.834
PT$IonPot[["Os"]] <- 8.438
PT$IonPot[["Ir"]] <- 8.967
PT$IonPot[["Pt"]] <- 8.959
PT$IonPot[["Au"]] <- 9.226
PT$IonPot[["Hg"]] <- 10.438
PT$IonPot[["Tl"]] <- 6.108
PT$IonPot[["Pb"]] <- 7.417
PT$IonPot[["Bi"]] <- 7.286
PT$IonPot[["Po"]] <- 8.417
PT$IonPot[["Th"]] <- 6.307
PT$IonPot[["U"]]  <- 6.194

# Electron affinity
PT$ElAff <- list()
PT$ElAff[["H"]]  <- 0.754
PT$ElAff[["He"]] <- -19.7
PT$ElAff[["Li"]] <- 0.618
PT$ElAff[["Be"]] <- -2.4
PT$ElAff[["B"]]  <- 0.280
PT$ElAff[["C"]]  <- 1.262
PT$ElAff[["N"]]  <- -1.4
PT$ElAff[["O"]]  <- 1.461
PT$ElAff[["F"]]  <- 3.401
#PT$ElAff[["Ne"]] <- 
PT$ElAff[["Na"]] <- 0.548
#PT$ElAff[["Mg"]] <- 
PT$ElAff[["Al"]] <- 0.433
PT$ElAff[["Si"]] <- 1.390
PT$ElAff[["P"]]  <- 0.747
PT$ElAff[["S"]]  <- 2.077
PT$ElAff[["Cl"]] <- 3.613
PT$ElAff[["Ar"]] <- -11.5
PT$ElAff[["K"]]  <- 0.501
PT$ElAff[["Ca"]] <- 0.025
PT$ElAff[["Sc"]] <- 0.188
PT$ElAff[["Ti"]] <- 0.084
PT$ElAff[["V"]]  <- 0.526
PT$ElAff[["Cr"]] <- 0.676
PT$ElAff[["Mn"]] <- -1
PT$ElAff[["Fe"]] <- 0.151
PT$ElAff[["Co"]] <- 0.663
PT$ElAff[["Ni"]] <- 1.157
PT$ElAff[["Cu"]] <- 1.236
#PT$ElAff[["Zn"]] <-  
PT$ElAff[["Ga"]] <- 0.43 
PT$ElAff[["Ge"]] <- 1.233
PT$ElAff[["As"]] <- 0.805
PT$ElAff[["Se"]] <- 2.021
PT$ElAff[["Br"]] <- 3.364
#PT$ElAff[["Kr"]] <- 
PT$ElAff[["Rb"]] <- 0.486
PT$ElAff[["Sr"]] <- 0.052
PT$ElAff[["Y"]]  <- 0.307
PT$ElAff[["Zr"]] <- 0.427
PT$ElAff[["Nb"]] <- 0.894
PT$ElAff[["Mo"]] <- 0.747
#PT$ElAff[["Tc"]] <- 
PT$ElAff[["Ru"]] <- 1.076
PT$ElAff[["Rh"]] <- 1.143
PT$ElAff[["Pd"]] <- 0.562
PT$ElAff[["Ag"]] <- 1.304
#PT$ElAff[["Cd"]] <- 
PT$ElAff[["In"]] <- 0.384 
PT$ElAff[["Sn"]] <- 1.112
PT$ElAff[["Sb"]] <- 1.047
PT$ElAff[["Te"]] <- 1.971
PT$ElAff[["I"]]  <- 3.059
PT$ElAff[["Xe"]] <- -0.056
PT$ElAff[["Cs"]] <- 0.472
PT$ElAff[["Ba"]] <- 0.145
PT$ElAff[["La"]] <- 0.47
PT$ElAff[["Ce"]] <- 0.57
PT$ElAff[["Pr"]] <- 0.962
PT$ElAff[["Nd"]] <- 0.162
PT$ElAff[["Pm"]] <- 0.129
PT$ElAff[["Sm"]] <- 0.162
PT$ElAff[["Eu"]] <- 0.116
PT$ElAff[["Gd"]] <- 0.137
PT$ElAff[["Tb"]] <- 0.436
PT$ElAff[["Dy"]] <- 0.352
PT$ElAff[["Ho"]] <- 0.338
PT$ElAff[["Er"]] <- 0.312
PT$ElAff[["Tm"]] <- 0.016 
PT$ElAff[["Yb"]] <- 0
PT$ElAff[["Lu"]] <- 0.34
#PT$ElAff[["Hf"]] <- 
PT$ElAff[["Ta"]] <- 0.323 
PT$ElAff[["W"]]  <- 0.816
PT$ElAff[["Re"]] <- 0.15
PT$ElAff[["Os"]] <- 1.078
PT$ElAff[["Ir"]] <- 1.564
PT$ElAff[["Pt"]] <- 2.125
PT$ElAff[["Au"]] <- 2.309
#PT$ElAff[["Hg"]] <- 
PT$ElAff[["Tl"]] <- 0.377 
PT$ElAff[["Pb"]] <- 0.364
PT$ElAff[["Bi"]] <- 0.942
PT$ElAff[["Po"]] <- 1.9
#PT$ElAff[["Th"]] <- 
#PT$EllAff[["U"]] <- 

# Color
PT$Color <- list()
PT$Color[["H"]]  <- "gray"
PT$Color[["He"]] <- "gray"
PT$Color[["Li"]] <- "blue4"
PT$Color[["Be"]] <- "gray"
PT$Color[["B"]]  <- "gray"
PT$Color[["C"]]  <- "cyan"
PT$Color[["N"]]  <- "blue"
PT$Color[["O"]]  <- "red"
PT$Color[["F"]]  <- "yellow"
PT$Color[["Ne"]] <- "gray"
PT$Color[["Na"]] <- "blue4"
PT$Color[["Mg"]] <- "gray"
PT$Color[["Al"]] <- "gray"
PT$Color[["Si"]] <- "gray"
PT$Color[["P"]]  <- "yellow"
PT$Color[["S"]]  <- "yellow"
PT$Color[["Cl"]] <- "green"
PT$Color[["Ar"]] <- "gray"
PT$Color[["K"]]  <- "blue4"
PT$Color[["Ca"]] <- "gray"
PT$Color[["Sc"]] <- "gray"
PT$Color[["Ti"]] <- "gray"
PT$Color[["V"]]  <- "gray"
PT$Color[["Cr"]] <- "gray"
PT$Color[["Mn"]] <- "gray"
PT$Color[["Fe"]] <- "red"
PT$Color[["Co"]] <- "blue"
PT$Color[["Ni"]] <- "gray"
PT$Color[["Cu"]] <- "green"
PT$Color[["Zn"]] <- "gray"
PT$Color[["Ga"]] <- "gray"
PT$Color[["Ge"]] <- "gray"
PT$Color[["As"]] <- "gray"
PT$Color[["Se"]] <- "yellow"
PT$Color[["Br"]] <- "yellow"
PT$Color[["Kr"]] <- "gray"
PT$Color[["Rb"]] <- "blue4"
PT$Color[["Sr"]] <- "gray"
PT$Color[["Y"]]  <- "gray"
PT$Color[["Zr"]] <- "gray"
PT$Color[["Nb"]] <- "gray"
PT$Color[["Mo"]] <- "gray"
PT$Color[["Tc"]] <- "gray"
PT$Color[["Ru"]] <- "gray"
PT$Color[["Rh"]] <- "gray"
PT$Color[["Pd"]] <- "gray"
PT$Color[["Ag"]] <- "white"
PT$Color[["Cd"]] <- "gray"
PT$Color[["In"]] <- "gray"
PT$Color[["Sn"]] <- "gray"
PT$Color[["Sb"]] <- "gray"
PT$Color[["Te"]] <- "gray"
PT$Color[["I"]]  <- "red"
PT$Color[["Xe"]] <- "gray"
PT$Color[["Cs"]] <- "blue4"
PT$Color[["Ba"]] <- "gray"
PT$Color[["La"]] <- "gray"
PT$Color[["Ce"]] <- "gray"
PT$Color[["Pr"]] <- "gray"
PT$Color[["Nd"]] <- "gray"
PT$Color[["Pm"]] <- "gray"
PT$Color[["Sm"]] <- "gray"
PT$Color[["Eu"]] <- "gray"
PT$Color[["Gd"]] <- "gray"
PT$Color[["Tb"]] <- "gray"
PT$Color[["Dy"]] <- "gray"
PT$Color[["Ho"]] <- "gray"
PT$Color[["Er"]] <- "gray"
PT$Color[["Tm"]] <- "gray"
PT$Color[["Yb"]] <- "gray"
PT$Color[["Lu"]] <- "gray"
PT$Color[["Hf"]] <- "gray"
PT$Color[["Ta"]] <- "gray"
PT$Color[["W"]]  <- "gray"
PT$Color[["Re"]] <- "gray"
PT$Color[["Os"]] <- "gray"
PT$Color[["Ir"]] <- "gray"
PT$Color[["Pt"]] <- "gray"
PT$Color[["Au"]] <- "yellow"
PT$Color[["Hg"]] <- "gray"
PT$Color[["Tl"]] <- "gray"
PT$Color[["Pb"]] <- "gray"
PT$Color[["Bi"]] <- "gray"
PT$Color[["Po"]] <- "gray"
PT$Color[["Th"]] <- "gray"
PT$Color[["U"]]  <- "gray"



